### ISSUE TITLE
`key:val` syntax in smart patterns is counterintuitive: it clashes with (most) account names

### ISSUE THREAD

**Issue by zacchiro** [zacchiro/beangrep#14]
`bean-grep Assets:Checking` is interpreted as `bean-grep --metadata Assets:Checking` :-(
The only decent fix is finding a proper one-character prefix to explicitely identify metadata.

**Comment by zacchiro** [comment]
@tbm what's ledger syntax to query on metadata key/value pairs? It can serve as inspiration here…

**Comment by tbm** [comment]
I don't think ledger will help.  It's complicated: `tag('foo') =~ /bar/"`

However, I believe hledger uses `tag:info`.   Oh, and `tag:foo=bar`.  See https://hledger.org/tags-tutorial.html#multiple-tags-in-a-query

The only problem with this is that beancount doesn't call it a "tag".  Maybe "meta:foo=bar"?

**Comment by tbm** [comment]
Wait a minute.  Beancount already has a clear distinction between account names and meta-data.  Account names are upper case whereas meta-data keys have to be lower-case.  So you could simply use that heuristic... no?  (Not sure if that changes in beancount v3)

**Comment by zacchiro** [comment]
Actually, it's even stricter: an account must start with one of the five account classes Assets/Liabilities/etc., so I'll base the heuristic detection on that. It would also allow to actually turn an account name into an `--account` predicate, rather than `--somewhere`.

**Comment by tbm** [comment]
> Actually, it's even stricter: an account must start with one of the five account classes Assets/Liabilities/etc

But don't forget that this can be configured with options!  (options `name_*`)

**Comment by zacchiro** [comment]
I didn't know that, thanks. But here we're talking about the smart pattern argument, which is really just a handy shorthand and nothing more. If the user has a specific non-standard setup, it's fair to expect them to use the explicit options (`--account`, `--somewhere`, etc.).
