### ISSUE TITLE
Should work even if journal has errors

### ISSUE THREAD

**Issue by tbm** [zacchiro/beangrep#5]
I have two errors in my journal right now. One is just because an `include` file glob doesn't match anything and another is a wrong balance check because I haven't updated/imported some credit card info.

Anyway, bean-grep shows me these errors:

```
Error: 
Beancount encountered error(s) when loading "books/2024":
LoadError(source={'filename': '<load>', 'lineno': 0}, message='File glob "../**/2024/*/*.beancount" does not match any files', entry=None)
BalanceError(source={'filename': '/home/tbm/finance/expenses/2024.beancount', 'lineno': 1753}, message="Balance failed for 'Assets:Voucher:Amazon': expected 0.00 USD != accumulated 1.60 USD (1.60 too much)", entry=Balance(meta={'filename': '/home/tbm/finance/expenses/2024.beancount', 'lineno': 1753}, date=datetime.date(2024, 4, 21), account='Assets:Voucher:Amazon', amount=0.00 USD, tolerance=None, diff_amount=None))
```

which is fair enough.

But it doesn't show any output.  I think I should still be able to grep my journal, even if there are errors.

**Comment by tbm** [comment]
I'm not sure if this is a separate issue or the same but I think the same.  But I have another good use case for ignoring *all* errors (really, that's for bean-check and not for bean-grep).

I split my journal into different files (one for each credit card / bank account, etc).  if I run bean-grep on my main journal (which includes all the other  files), all is good.

But sometimes maybe I only want to search in one specific file... but when I do this, I get a lot of errors because of `__tolerances__': {'PHP': Decimal('0.005')}`.  My main journal file has `inferred_tolerance_default` statements but of course individual files don't.

I think that's another good case for simply ignoring errors (don't even display them?).

**Comment by zacchiro** [comment]
I've thought about this, but what was difficult for me is determining which errors warrant aborting execution (without even trying to grep anything) and which don't.

I strongly believe that if the requested file cannot be loaded, then we have to abort execution (with exit code 2).
Everything else can probably be ignored, and logged as a warning.

If someone can look into how to determine this on top of the error types returned by the Beancount load API, I'll be happy to implement it.

**Comment by tbm** [comment]
I asked Daniele Nicolodi by email if we can comment on this.

**Comment by dnicolodi** [comment]
Hello @tbm, @zacchiro. You can ping me directly with a mention on GitHub next time 🙂 

I don't know if there is a correct answer. What bean-query does is to print the errors and proceed, on all errors that are not fatal for `beancount.loader.load_file()`. The beancount parser is pretty resilient and usually recovers reasonably from malformed input. Errors from booking should not be fatal for tools intended to inspect Beancount ledgers.

**Comment by zacchiro** [comment]
@dnicolodi hello, and thanks for your feedback.
The main problem I encountered is how to (programmatically) determine if an error is "fatal" or not.
Can you point me to where bean-query determines that?

FWIW, what I ended up doing for now in bean-grep is to ignore *all* Beancount load errors (informing the user about their presence with warnings), and make bean-grep fail itself only if 0 entries have been loaded. Which seems to work quite well in practice.

**Comment by dnicolodi** [comment]
With "fatal" I meant `beancount.loader.load_file()` raising an exception, which IIRC should happen only if the file cannot be read at all. All errors reported in the errors array returned by `load_file()` are reported but ignored.
