### ISSUE TITLE
Support configuration file, to override defaults

### ISSUE THREAD

**Issue by tbm** [zacchiro/beangrep#8]
`--help` says stuff like `[default: no-ignore-case]`.  Is there a config file to change the defaults. That would be useful for e.g. ignore-case.

(If only there was a man page...!)

According to the source there's no config file.

**Comment by zacchiro** [comment]
I'm not against this, but not very motivated to implement it myself. Hence tagging this as "help wanted", as a call for patches. 

As preferred format for the configuration file I'd say either toml (as we already have pyproject.toml) or yaml (which is probably more common for users still, and less quirky than json). Definitely *not* Python's ConfigParser.

**Comment by tbm** [comment]
The latest version works exactly out of the box the way I like it, so I'm personally not too bothered by this anymore.

**Comment by zacchiro** [comment]
> As preferred format for the configuration file I'd say either toml (as we already have pyproject.toml) or yaml (which is probably more common for users still, and less quirky than json).

Actually, something even simpler is probably the way to go.
Taking inspiration from ripgrep: one `beangreprc` file, containing one CLI option per line (e.g., `--ignore-case`).

**Comment by tbm** [comment]
true, good idea
