### ISSUE TITLE
Search multiple files

### ISSUE THREAD

**Issue by tbm** [zacchiro/beangrep#9]
I split my beancount files per year.  So it would be nice to specify multiple FILENAME to search in several years.

I don't know how hard this is to implement. Maybe this makes no sense. Feel free to close.

**Comment by zacchiro** [comment]
It's easy to implement and makes sense. Also, it makes it closer to standard `grep` UX, which is sort of a design principle for `bean-grep`.

**Comment by tbm** [comment]
If multiple PATTERNs (#11) and FILENAMEs are allowed, how would you distinguish the two?  Check if the file exists? If yes, FILENAME. If not, PATTERN?

**Comment by zacchiro** [comment]
Note that #9 and #11 together can make the parsing of arguments ambiguous.

**Comment by zacchiro** [comment]
@tbm can you test the `feature/multiple-files` branch?
This feature request is implemented there, but I'd love some user testing before merging into `main`.

**Comment by tbm** [comment]
sorry, I didn't have time yet. I'll try to check it out soon. Thanks!
